### ISSUE TITLE
failed to reveal

### ISSUE THREAD

**Issue by cryptoale74** [kyokan/bob-wallet#588] opened 2023-01-08 00:30 UTC
## Current Behavior
 trying to reveal the bid error accours

## Steps to Reproduce

1.
1.
1.
1.

**Comment by cryptoale74** [comment] 2023-01-08 00:30
how can i send you the log??

**Comment by rithvikvibhu** [comment] 2023-02-18 07:17
closing as duplicate of https://github.com/kyokan/bob-wallet/issues/587

**Closed by rithvikvibhu** 2023-02-18 07:17 UTC
