### ISSUE TITLE
[Feature] Bids w/ Customizable Fee

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#156] opened 2020-07-01 16:42 UTC
As of 0.3.0 we only support fee customization in Send View.
It should be straightforward to port the code to bid view or generalize it somehow when sending any transaction.

**Comment by mslipper** [comment] 2020-07-05 19:42
This is unfortunately non-trivial, as the `hsd` RPC auction commands do not support setting the fee.

**Comment by pinheadmz** [comment] 2020-07-21 21:27
TX fees using rpc should be configurable using https://hsd-dev.org/api-docs/#settxfee

**Comment by rithvikvibhu** [comment] 2022-02-21 15:25
Dupe of #127, tracking there.

**Closed by rithvikvibhu** 2022-02-21 15:25 UTC
