### ISSUE TITLE
Bids are not showing for actively auctioning domains.

### ISSUE THREAD

**Issue by cballou** [kyokan/bob-wallet#129] opened 2020-04-22 16:11 UTC
Auctions with active bids on them are not displaying any bid history on my local client. I confirmed bids by simply comparing against Namebase.

## Expected Behavior
1. Search for domain `dpos`
1. The list of bids should be displayed.

## Current Behavior
1. Search for domain `dpos`
1. No bids are displayed, but bids verified to exist at https://www.namebase.io/domains/dpos

## Context (Environment)
* OSX Mojave 10.14.5
* Latest v0.2.8 .dmg
* Network: Mainnet

## Logs
* Exported `bob-debug.log` but it's empty

## Screencap

[image](https://i.imgur.com/5bIpmW2.png)

**Comment by pinheadmz** [comment] 2020-04-29 10:34
Duplicate of https://github.com/kyokan/bob-wallet/issues/108

This has been addressed and will be available in the next release!

**Closed by pinheadmz** 2020-04-29 10:34 UTC
